version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: concurrency-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservation_db
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7.0-alpine
    container_name: concurrency-redis
    ports:
      - "6379:6379"

volumes:
  mysql-data: